:jbake-title: Runtime View
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: arc42
:jbake-order: 6
:filename: /chapters/06_runtime_view.adoc
ifndef::imagesdir[:imagesdir: ../../images]

:toc:

ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View

=== Create Club Workflow

After a club was created the following workflow happens to configure the digital office and the club forum:

.Create Club for digital office runtime view
image::../../../src/docs/images/runtime_view_club_creation_new.svg[]

A _HELD Member_ creates a new club via the _Hero Portal Web UI_. If the save button is clicked, then a backend call via REST API to the _Hero Portal Backend_ is done. The backend saves the club in the database, sends a club created event to kafka and returns a positive response to the Web UI. 

After the club created event appears on the kafka message bus, the _Digital Office Sidecar Backend_ starts the configuration process. Folders, groups and shares are configured to nextcloud directly. The assignment of the users to the groups works via client roles in keycloak. If a user has a client role with the same name as a nextcloud group, than the user is directly member of this group. 

In parallel to the _Digital Office_ configuration, the _Club Forum_ configuration is done. The _Club Forum Sidecar Backend_ receives the club created event and configures discourse directly.