ifndef::imagesdir[:imagesdir: ../images]

=== Styleguide

SNS besteht aus drei völlig autonomen Anwendungen. Das visuelle Erscheinungsbild der Anwendungen ist weitestgehend
identisch, sodass für Benutzer der Wechsel zwischen den Anwendungen nicht als visueller Bruch anmutet. Erreicht wird
dies durch einen einheitlichen Styleguide, welcher isoliert entwickelt wird und von jeder Anwendung verwendet wird.

Der Quellcode des UBA-Styleguides den SNS verwendet ist hier verfügbar: https://github.com/innoq/uba-bootstrap-theme

Technisch basiert der Styleguide auf Bootstrap 5. Der Styleguide wird von jeder Anwendung als NPM-Dependency in
der Datei `package.json` referenziert. Die jeweilige Anwendung zieht die zentralen Assets (Stylesheets, Javascript,
Bilder und Schriften) zur Build-Zeit während des Deployments an. Es ist also möglich, dass die Anwendungen auf
verschiedenen Versionen des zentralen Styleguides basieren. Zusätzlich zu den zentralen Assets definieren die
Anwendungen auch spezifische Stylesheets und Javascript-Funktionen.

Bei Aktualisierung der verwendeten Bootstrap-Version muss als erstes der zentrale Styleguide aktualisiert werden.
Anschließend muss ggf. das HTML-Markup aller iQvoc-Anwendungen auf die neue Version angepasst werden.
